### ISSUE TITLE
Disallow old-style positional only args (starting with double underscore)

### ISSUE THREAD

**Issue by srittau** [PyCQA/flake8-pyi#447] opened 2023-11-10 07:11 UTC

**Comment by AlexWaygood** [comment] 2023-11-10 08:35
Duplicate of #173

**Closed by AlexWaygood** 2023-11-10 08:35 UTC
Labels: type-feature

**Comment by srittau** [comment] 2023-11-10 09:16
I guess I should not open issues in the morning...

**Comment by AlexWaygood** [comment] 2023-11-10 09:23
https://youtu.be/gAWpHbV6cwc?si=Z5LgsKmYEgQBdlH0
